import { UserProfile } from '../types';

export const personas: Record<string, UserProfile> = {
  divyansh: {
    id: 'persona_divyansh',
    personaId: 'divyansh',
    fullName: 'Divyansh Joshi',
    email: 'divyansh.joshi@example.com',
    phone: '+91 98765 43210',
    headline: 'B.Tech CSE AI & Data Science Candidate',
    university: 'Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)',
    degree: 'Bachelor of Technology (B.Tech)',
    major: 'AI & Data Science',
    gradYear: '2027',
    cgpa: '8.4 / 10.0',
    location: 'Bhopal, Madhya Pradesh',
    bio: 'Aspiring Software & AI Systems Engineer with focus on Python backend microservices, SQL databases, and algorithmic problem solving.',
    targetCareerId: 'career_software_eng',
    targetTimeline: 'Summer 2027',
    preferredWorkType: ['Remote', 'Hybrid', 'On-site'],
    preferredLocations: ['Bhopal', 'Indore', 'Delhi NCR', 'Bengaluru', 'Remote'],
    skills: [
      { name: 'Python', level: 'Advanced', verified: true },
      { name: 'SQL', level: 'Intermediate', verified: true },
      { name: 'Java', level: 'Intermediate', verified: true },
      { name: 'React', level: 'Intermediate', verified: true },
      { name: 'Git', level: 'Intermediate', verified: true },
      { name: 'Problem Solving', level: 'Advanced', verified: true },
      { name: 'REST APIs', level: 'Beginner', verified: false },
      { name: 'DSA', level: 'Intermediate', verified: false },
    ],
    experiences: [
      {
        id: 'exp_1',
        role: 'Backend Engineering Intern',
        company: 'TechLabs Solutions',
        location: 'Bhopal (Hybrid)',
        startDate: 'May 2025',
        endDate: 'July 2025',
        description: 'Worked on internal dashboard services and database optimization.',
        highlights: [
          'Developed 6 RESTful endpoints using Python and SQLite for internal equipment tracking.',
          'Reduced query execution times by 28% through multi-column indexing on student attendance tables.',
          'Wrote unit tests achieving 78% code coverage using pytest.',
        ],
      },
    ],
    projects: [
      {
        id: 'proj_user_1',
        title: 'Student Expense Tracking API',
        role: 'Lead Developer',
        techStack: ['Python', 'FastAPI', 'SQLite', 'Pytest'],
        summary: 'A lightweight financial tracking API for university students with JWT authentication.',
        bullets: [
          'Engineered JWT authenticated REST service handling budget tracking across 12 expense categories.',
          'Implemented automated Swagger API documentation with schema validations via Pydantic.',
          'Integrated GitHub Actions CI pipeline running automated linting and test suites on every pull request.',
        ],
        link: 'https://github.com/divyansh/student-expense-api',
      },
    ],
    resumeUploaded: true,
    resumeFileName: 'Divyansh_Joshi_Resume_2026.pdf',
    resumeAtsScore: 78,
    resumeLastAnalyzed: 'Today, 2:30 PM',
    resumeSummary: 'Student candidate in B.Tech CSE AI & DS with strong Python and SQL foundations, pursuing junior/intern software engineering roles.',
  },
  pooja: {
    id: 'persona_pooja',
    personaId: 'pooja',
    fullName: 'Pooja Sharma',
    email: 'pooja.sharma@example.com',
    phone: '+91 98261 54321',
    headline: 'Commerce Graduate Transitioning to Data & Business Analytics',
    university: 'Barkatullah University, Bhopal',
    degree: 'Bachelor of Commerce (B.Com)',
    major: 'Financial Accounting & Analytics',
    gradYear: '2026',
    cgpa: '7.8 / 10.0',
    location: 'Indore, Madhya Pradesh',
    bio: 'Commerce graduate transitioning into Data Analytics and Business Intelligence, leveraging structured Excel modeling, accounting knowledge, and SQL.',
    targetCareerId: 'career_data_analyst',
    targetTimeline: 'Within 3 Months',
    preferredWorkType: ['Remote', 'Hybrid'],
    preferredLocations: ['Indore', 'Bhopal', 'Remote'],
    skills: [
      { name: 'Excel / Spreadsheets', level: 'Advanced', verified: true },
      { name: 'Problem Solving', level: 'Intermediate', verified: true },
      { name: 'Accounting', level: 'Advanced', verified: true },
      { name: 'Business Communication', level: 'Advanced', verified: true },
      { name: 'SQL', level: 'Beginner', verified: false },
    ],
    experiences: [],
    projects: [
      {
        id: 'proj_pooja_1',
        title: 'SME Financial Audit & Inventory Turnaround Model',
        role: 'Analyst',
        techStack: ['MS Excel', 'Financial Statements', 'Pivot Tables'],
        summary: 'Quarterly balance sheet modeling and inventory turnover tracking dashboard.',
        bullets: [
          'Built spreadsheet dashboards tracking inventory turnover and overdue receivables.',
          'Identified 18% working capital blockage in retail supply chain logs.',
        ],
      },
    ],
    resumeUploaded: true,
    resumeFileName: 'Pooja_Sharma_Commerce_Resume.pdf',
    resumeAtsScore: 72,
    resumeLastAnalyzed: 'Today, 11:00 AM',
    resumeSummary: 'Non-tech B.Com graduate exploring data analytics pathways, PMKVY certifications, and state apprenticeship schemes.',
  },
  rahul: {
    id: 'persona_rahul',
    personaId: 'rahul',
    fullName: 'Rahul Verma',
    email: 'rahul.verma@example.com',
    phone: '+91 97523 11223',
    headline: 'Polytechnic Diploma Holder Seeking MMSKY / NAPS Apprenticeship',
    university: 'Government Polytechnic College, Sagar, MP',
    degree: 'Polytechnic Diploma',
    major: 'Computer Engineering & Networking',
    gradYear: '2025',
    cgpa: '7.6 / 10.0',
    location: 'Sagar / Jabalpur, Madhya Pradesh',
    bio: 'Polytechnic Diploma graduate from Sagar, MP seeking on-the-job industrial apprenticeship under Mukhyamantri Seekho Kamao Yojana (MMSKY).',
    targetCareerId: 'career_digital_india_tech',
    targetTimeline: 'Within 1 Month',
    preferredWorkType: ['On-site', 'Hybrid'],
    preferredLocations: ['Sagar', 'Jabalpur', 'Bhopal'],
    skills: [
      { name: 'Hardware & Networking', level: 'Advanced', verified: true },
      { name: 'Linux', level: 'Intermediate', verified: true },
      { name: 'Web Development', level: 'Beginner', verified: true },
      { name: 'SQL', level: 'Beginner', verified: true },
    ],
    experiences: [],
    projects: [
      {
        id: 'proj_rahul_1',
        title: 'College Lab Local Area Network Configuration',
        role: 'Hardware Lead',
        techStack: ['Linux', 'LAN Routing', 'Apache Server'],
        summary: 'Configured local subnet routing and static IP leases for 40 laboratory workstations.',
        bullets: [
          'Configured local subnet routing and static IP leases for 40 laboratory workstations.',
          'Set up local intranet file sharing service on Ubuntu server with zero packet drops.',
        ],
      },
    ],
    resumeUploaded: true,
    resumeFileName: 'Rahul_Verma_Diploma_Resume.pdf',
    resumeAtsScore: 68,
    resumeLastAnalyzed: 'Yesterday',
    resumeSummary: 'Diploma holder from tier-3 MP town seeking technical apprenticeship and MMSKY stipend allocation.',
  },
};
