import {
  UserProfile,
  CareerPath,
  SkillItem,
  SkillGap,
  Course,
  Project,
  Opportunity,
  RoadmapMilestone,
  MockInterviewQuestion,
  GovtScheme,
} from '../types';

export const initialUserProfile: UserProfile = {
  id: 'usr_guest',
  personaId: undefined,
  fullName: 'New Candidate',
  email: 'candidate@university.edu',
  phone: '',
  headline: 'Engineering Student • Awaiting Resume Upload',
  university: 'University / Institute',
  degree: 'Bachelor of Technology (B.Tech)',
  major: 'Computer Science',
  gradYear: '2027',
  cgpa: '',
  location: 'Madhya Pradesh / Remote',
  bio: 'Upload your resume (PDF, DOCX, TXT) to automatically calibrate your Career OS, extract verified technical competencies, and calculate target role compatibility.',
  targetCareerId: 'career_software_eng',
  targetTimeline: 'Summer 2027',
  preferredWorkType: ['Remote', 'Hybrid', 'On-site'],
  preferredLocations: ['Bhopal', 'Indore', 'Bengaluru', 'Remote'],
  skills: [],
  experiences: [],
  projects: [],
  resumeUploaded: false,
  resumeFileName: undefined,
  resumeAtsScore: undefined,
  resumeLastAnalyzed: undefined,
  resumeSummary: undefined,
};

export const skillsCatalogue: SkillItem[] = [
  {
    id: 'skill_dsa',
    name: 'DSA',
    category: 'Core CS',
    userLevel: 'Intermediate',
    requiredLevel: 'Advanced',
    importance: 'Critical',
    inDemandScore: 92,
    mappedCourseId: 'course_dsa_foundations',
    mappedProjectIds: ['proj_student_expense_api'],
    description: 'Solve 30 problems + build one feature.',
  },
  {
    id: 'skill_sql',
    name: 'SQL',
    category: 'Cloud & Systems',
    userLevel: 'Intermediate',
    requiredLevel: 'Advanced',
    importance: 'Critical',
    inDemandScore: 88,
    mappedCourseId: 'course_sql_developers',
    mappedProjectIds: ['proj_student_expense_api'],
    description: 'Practice joins, indexes & query optimization.',
  },
  {
    id: 'skill_system_design',
    name: 'System Design',
    category: 'Core CS',
    userLevel: 'Beginner',
    requiredLevel: 'Intermediate',
    importance: 'Important',
    inDemandScore: 85,
    mappedCourseId: 'course_build_rest_api',
    mappedProjectIds: ['proj_career_tracker'],
    description: 'Learn architecture patterns.',
  },
  {
    id: 'skill_testing',
    name: 'Testing',
    category: 'Frameworks',
    userLevel: 'Beginner',
    requiredLevel: 'Intermediate',
    importance: 'Important',
    inDemandScore: 78,
    mappedCourseId: 'course_build_rest_api',
    mappedProjectIds: ['proj_student_expense_api'],
    description: 'Write tests for your next project.',
  },
  {
    id: 'skill_rest_apis',
    name: 'REST APIs',
    category: 'Frameworks',
    userLevel: 'Beginner',
    requiredLevel: 'Advanced',
    importance: 'Critical',
    inDemandScore: 90,
    mappedCourseId: 'course_build_rest_api',
    mappedProjectIds: ['proj_student_expense_api'],
    description: 'Missing evidence in your current profile. Suggested proof: Build a real API with FastAPI.',
  },
];

export const careerPaths: CareerPath[] = [
  {
    id: 'career_software_eng',
    slug: 'software-engineer',
    title: 'Software Development Engineer',
    category: 'Software Engineering',
    shortDescription: 'Build scalable products and systems.',
    fullDescription: 'Software engineers build reliable, scalable architectures, backend services, and interactive user interfaces.',
    matchScore: 82,
    marketDemand: 'Very High',
    avgSalary: '₹7,50,000 - ₹14,00,000',
    openingsEstimate: '12,000+ Active Roles',
    isTarget: true,
    growthRate: '+24% YoY',
    topHiringCompanies: ['TCS', 'Infosys', 'ABC Technologies', 'Persistent Systems', 'Zoho'],
    requiredSkills: [
      { skillId: 'skill_python', name: 'Python', level: 'Advanced', userMatches: true },
      { skillId: 'skill_sql', name: 'SQL', level: 'Advanced', userMatches: true },
      { skillId: 'skill_dsa', name: 'DSA', level: 'Advanced', userMatches: false },
      { skillId: 'skill_rest_apis', name: 'REST APIs', level: 'Advanced', userMatches: false },
      { skillId: 'skill_system_design', name: 'System Design', level: 'Intermediate', userMatches: false },
    ],
    whyMatchRationale: {
      strengths: [
        'Matches your goals + current skills in Python, Git, and SQL foundations',
        'Strong problem solving and computer science coursework alignment',
      ],
      gaps: [
        'Missing proof artifact for production REST APIs',
        'Solve 15 more medium DSA problem sets',
      ],
      verdict: 'High-probability trajectory. Completing the Student Expense API project bridges the remaining 18% readiness delta.',
    },
  },
  {
    id: 'career_data_analyst',
    slug: 'data-analyst',
    title: 'Data Analyst & Business Intelligence',
    category: 'Data & Analytics',
    shortDescription: 'Turn enterprise business data into decisions.',
    fullDescription: 'Data analysts transform raw datasets into dashboards, reports, and predictive metrics to guide strategic decisions.',
    matchScore: 74,
    marketDemand: 'High',
    avgSalary: '₹5,00,000 - ₹9,50,000',
    openingsEstimate: '9,800+ Active Roles',
    isTarget: false,
    growthRate: '+20% YoY',
    topHiringCompanies: ['Deloitte', 'EY', 'KPMG', 'Genpact', 'Mu Sigma'],
    requiredSkills: [
      { skillId: 'skill_python', name: 'Python', level: 'Advanced', userMatches: true },
      { skillId: 'skill_sql', name: 'SQL', level: 'Advanced', userMatches: true },
      { skillId: 'skill_dsa', name: 'DSA', level: 'Intermediate', userMatches: false },
    ],
    whyMatchRationale: {
      strengths: ['Solid foundation in SQL query operations and data manipulation'],
      gaps: ['Requires deeper exploratory data analysis and dashboarding proof'],
      verdict: 'Good secondary path with strong analytical overlap.',
    },
  },
  {
    id: 'career_ai_ml_eng',
    slug: 'ai-ml-engineer',
    title: 'AI & Machine Learning Engineer',
    category: 'Artificial Intelligence',
    shortDescription: 'Build intelligent systems, LLM pipelines, and models.',
    fullDescription: 'Train, evaluate, and deploy machine learning models and LLM agent systems into production pipelines.',
    matchScore: 69,
    marketDemand: 'Very High',
    avgSalary: '₹8,50,000 - ₹18,00,000',
    openingsEstimate: '6,400+ Active Roles',
    isTarget: false,
    growthRate: '+45% YoY',
    topHiringCompanies: ['Fractal Analytics', 'Tiger Analytics', 'Amazon India', 'Google IDC'],
    requiredSkills: [
      { skillId: 'skill_python', name: 'Python', level: 'Advanced', userMatches: true },
      { skillId: 'skill_sql', name: 'SQL', level: 'Intermediate', userMatches: true },
      { skillId: 'skill_dsa', name: 'DSA', level: 'Advanced', userMatches: false },
    ],
    whyMatchRationale: {
      strengths: ['Enrolled in B.Tech CSE AI & Data Science specialization'],
      gaps: ['Requires verified deep learning and transformer architecture artifacts'],
      verdict: 'High-growth trajectory requiring advanced math and model tuning milestones.',
    },
  },
];

export const skillGaps: SkillGap[] = [
  {
    skill: skillsCatalogue[0], // DSA
    currentScore: 55,
    requiredScore: 85,
    gapScore: 30,
    status: 'Action Needed',
    recommendedAction: 'Solve 30 problems + build one feature.',
    estimatedHoursToClose: 14,
  },
  {
    skill: skillsCatalogue[1], // SQL
    currentScore: 65,
    requiredScore: 88,
    gapScore: 23,
    status: 'Action Needed',
    recommendedAction: 'Practice joins, indexes & query optimization.',
    estimatedHoursToClose: 8,
  },
  {
    skill: skillsCatalogue[2], // System Design
    currentScore: 40,
    requiredScore: 75,
    gapScore: 35,
    status: 'In Progress',
    recommendedAction: 'Learn architecture patterns.',
    estimatedHoursToClose: 12,
  },
  {
    skill: skillsCatalogue[3], // Testing
    currentScore: 45,
    requiredScore: 70,
    gapScore: 25,
    status: 'In Progress',
    recommendedAction: 'Write tests for your next project.',
    estimatedHoursToClose: 6,
  },
];

export const courses: Course[] = [
  {
    id: 'course_nptel_dsa',
    slug: 'nptel-dsa-python',
    title: 'Programming & Data Structures in Python',
    provider: 'NPTEL / IIT Madras (SWAYAM)',
    level: 'Intermediate',
    duration: '8 Weeks (30 Hours)',
    description: 'Master core data structures, recursive patterns, trees, and algorithmic design principles directly credited to college transcripts.',
    skillsTaught: ['Python', 'DSA', 'Time Complexity', 'Problem Solving'],
    modulesCount: 4,
    enrolled: true,
    progressPercent: 55,
    rating: 4.9,
    reviewCount: 8420,
    badgeName: 'NPTEL Silver Elite',
    url: 'https://swayam.gov.in/explorer?searchText=Data+Structures+Python',
    isFree: true,
    nepCredits: '2 AICTE / NEP Credit Units',
    modules: [
      { id: 'm1', title: 'Arrays, Strings & HashMaps', duration: '2h 15m', completed: true, topics: ['Prefix sums', 'Sliding window', 'Hash frequency'] },
      { id: 'm2', title: 'Binary Search & Sorting', duration: '2h 30m', completed: true, topics: ['Divide and conquer', 'Search rotated array'] },
      { id: 'm3', title: 'Trees, Inorder Traversal & BFS', duration: '2h 45m', completed: false, topics: ['Binary Search Tree', 'Level-order traversal'] },
      { id: 'm4', title: 'Graph Traversal & Shortest Path', duration: '2h 30m', completed: false, topics: ['DFS/BFS', 'Dijkstra basics'] },
    ],
  },
  {
    id: 'course_nptel_dbms',
    slug: 'nptel-dbms',
    title: 'Database Management Systems & Indexing',
    provider: 'NPTEL / IIT Kharagpur (SWAYAM)',
    level: 'Intermediate',
    duration: '8 Weeks (25 Hours)',
    description: 'Learn complex JOINs, multi-column B-tree indexes, query plan profiling, and ACID transaction isolation guarantees.',
    skillsTaught: ['SQL', 'Query Optimization', 'Indexes', 'ACID Transactions'],
    modulesCount: 3,
    enrolled: false,
    progressPercent: 0,
    rating: 4.8,
    reviewCount: 6120,
    badgeName: 'SQL Database Specialist',
    url: 'https://swayam.gov.in/explorer?searchText=Database+Management+System',
    isFree: true,
    nepCredits: '2 AICTE / NEP Credit Units',
    modules: [
      { id: 'm1', title: 'Advanced Joins & Aggregations', duration: '2h', completed: false, topics: ['Inner/Outer/Cross joins', 'GROUP BY HAVING'] },
      { id: 'm2', title: 'Indexing & EXPLAIN Query Analysis', duration: '2h', completed: false, topics: ['Index scan vs Seq scan', 'Covering indexes'] },
      { id: 'm3', title: 'Transactions & ACID guarantees', duration: '2h', completed: false, topics: ['Isolation levels', 'Locking'] },
    ],
  },
  {
    id: 'course_skill_india_fullstack',
    slug: 'skill-india-fastapi',
    title: 'Production REST APIs with FastAPI',
    provider: 'Skill India Digital Hub (NSDC)',
    level: 'Intermediate',
    duration: '6 Weeks (40 Hours)',
    description: 'Step-by-step guidance on constructing production RESTful web services with FastAPI, SQLAlchemy, and JWT authentication.',
    skillsTaught: ['FastAPI', 'REST APIs', 'SQLAlchemy', 'JWT Auth'],
    modulesCount: 4,
    enrolled: false,
    progressPercent: 0,
    rating: 4.92,
    reviewCount: 4200,
    badgeName: 'NSDC Certified Backend Specialist',
    url: 'https://www.skillindiadigital.gov.in/',
    isFree: true,
    nepCredits: '3 NSDC Micro-Credentials',
    modules: [
      { id: 'm1', title: 'HTTP Methods, Headers & Status Codes', duration: '1h 30m', completed: false, topics: ['Idempotency', 'Response codes'] },
      { id: 'm2', title: 'FastAPI Schemas & Pydantic Validation', duration: '2h', completed: false, topics: ['Request bodies', 'Type safety'] },
      { id: 'm3', title: 'Database Integration with SQLite & Postgres', duration: '2h 30m', completed: false, topics: ['Session management', 'Migrations'] },
      { id: 'm4', title: 'Authentication & Unit Testing with Pytest', duration: '2h', completed: false, topics: ['JWT bearer tokens', 'Fixtures'] },
    ],
  },
];

export const projects: Project[] = [
  {
    id: 'proj_student_expense_api',
    slug: 'student-expense-api',
    title: 'Student Expense API',
    category: 'REST APIs • FastAPI • SQL',
    difficulty: 'Intermediate',
    estHours: 12,
    summary: 'A portfolio-grade backend project designed around your missing REST API skills.',
    description: 'Build a real API with FastAPI covering SQL database integration, user authentication, automated testing, and cloud deployment.',
    keySkills: ['REST APIs', 'FastAPI', 'SQL', 'Authentication'],
    skillsClosed: ['REST APIs', 'SQL', 'Testing'],
    deliverables: [
      'GitHub repository with comprehensive README and API demo video',
      'Secure JWT authentication and password hashing',
      'Comprehensive Pytest test suite with >80% coverage',
    ],
    starterRepoUrl: 'https://github.com/pragya-os/starter-student-expense-api',
    prerequisites: ['Basic Python syntax', 'SQL fundamentals'],
    architectureOverview: 'FastAPI service with SQLAlchemy ORM, SQLite/PostgreSQL store, and automated Swagger/OpenAPI docs.',
    completed: false,
    featured: true,
  },
  {
    id: 'proj_career_tracker',
    slug: 'career-tracker',
    title: 'Career Tracker',
    category: 'React • Next.js • Auth',
    difficulty: 'Intermediate',
    estHours: 10,
    summary: 'Start from roadmap: interactive career goals and progress tracking web app.',
    description: 'Build a full-stack tracking dashboard with React, Next.js, and authenticated persistent state.',
    keySkills: ['React', 'Next.js', 'Authentication', 'State Management'],
    skillsClosed: ['React', 'System Design'],
    deliverables: [
      'Interactive pipeline kanban board with drag-and-drop',
      'PostgreSQL schema with user authentication',
    ],
    starterRepoUrl: 'https://github.com/pragya-os/starter-career-tracker',
    prerequisites: ['React basics'],
    architectureOverview: 'React client with PostgreSQL persistent store.',
    completed: true,
    featured: false,
  },
];

export const opportunities: Opportunity[] = [
  {
    id: 'opp_abc_tech_software',
    slug: 'software-engineering-intern-abc',
    title: 'Software Development Intern',
    company: 'ABC Technologies',
    location: 'Bhopal / Remote',
    type: 'Internship',
    workplaceType: 'Remote',
    salaryRange: '₹25,000 / month',
    matchScore: 92,
    readinessLabel: 'Ready to Apply',
    deadline: 'Oct 15, 2026',
    postedDate: '2 days ago',
    description: 'ABC Technologies is hiring an engineering intern to assist in building backend APIs, optimizing database queries, and integrating frontend components.',
    applyUrl: 'https://careers.abctechnologies.com/jobs/intern-backend-bhopal',
    requirements: [
      { requirement: 'Python proficiency', satisfied: true, mandatory: true },
      { requirement: 'SQL & Database fundamentals', satisfied: true, mandatory: true },
      { requirement: 'Git version control', satisfied: true, mandatory: true },
      { requirement: 'HTML/CSS basics', satisfied: true, mandatory: true },
      { requirement: 'REST APIs evidence', satisfied: false, mandatory: false },
    ],
    matchedSkills: ['Python', 'SQL', 'Git', 'Problem Solving'],
    missingSkills: ['REST APIs'],
    stage: 'Saved',
    whyMatchDetails: {
      overallFit: 92,
      skillOverlapScore: 90,
      experienceScore: 92,
      educationScore: 94,
      summary: 'Matches your career goal + 4 core skills + education in CSE AI & Data Science.',
      advantages: [
        'Strong academic foundation in computer science and algorithms',
        'Verified project evidence in Python and Git collaboration',
      ],
      riskFactors: [
        'Strengthening REST APIs would improve your alignment with similar backend roles.',
      ],
    },
  },
  {
    id: 'opp_persistent_cloud_trainee',
    slug: 'cloud-trainee-persistent',
    title: 'Cloud & Software Trainee Engineer',
    company: 'Persistent Systems',
    location: 'Indore / Pune',
    type: 'Full-time',
    workplaceType: 'Hybrid',
    salaryRange: '₹5,50,000 / year',
    matchScore: 84,
    readinessLabel: 'Ready to Apply',
    deadline: 'Oct 28, 2026',
    postedDate: '3 days ago',
    description: 'Join Persistent early career cohort. Work across cloud-native applications, microservices testing, and backend pipelines.',
    applyUrl: 'https://www.persistent.com/careers/early-careers',
    requirements: [
      { requirement: 'B.Tech/BE in CS, IT, AI or related engineering stream with >=60%', satisfied: true, mandatory: true },
      { requirement: 'Data Structures & Algorithms in Python/Java', satisfied: true, mandatory: true },
      { requirement: 'Relational database SQL understanding', satisfied: true, mandatory: true },
    ],
    matchedSkills: ['Python', 'SQL', 'Problem Solving'],
    missingSkills: ['Docker', 'AWS'],
    stage: 'Saved',
    whyMatchDetails: {
      overallFit: 84,
      skillOverlapScore: 82,
      experienceScore: 84,
      educationScore: 88,
      summary: 'Strong academic match from RGPV MP with high problem-solving foundations.',
      advantages: ['Campus hiring tier alignment and verified programming skills'],
      riskFactors: ['Add cloud deployment notes to your resume project bullets'],
    },
  },
];

export const govtSchemes: GovtScheme[] = [
  {
    id: 'scheme_mmsky',
    name: 'Mukhyamantri Seekho-Kamao Yojana (MMSKY)',
    category: 'State Govt Scheme (Madhya Pradesh)',
    ministryOrDept: 'Dept of Technical Education, Skill Development & Employment, MP',
    portalName: 'MMSKY MP Official Portal',
    portalUrl: 'https://mmsky.mp.gov.in/',
    monthlyStipendInr: '₹10,000 / month (Graduates/Engineers)',
    targetAudience: '12th Pass, ITI, Diploma & B.Tech / Graduate youth resident in MP',
    description: 'Flagship Madhya Pradesh initiative providing on-the-job industrial training across 46 sectors. State government directly transfers 75% of the stipend to the candidate\'s Aadhaar-linked bank account (DBT).',
    benefits: [
      'Direct Benefit Transfer (DBT) into trainee bank account',
      '₹10,000/mo for engineering graduates, ₹9,000/mo for Diploma holders',
      'State-recognized SCVT industrial certification',
      'High conversion probability into permanent employment',
    ],
    eligible: true,
    reasons: [
      'Resident of Madhya Pradesh (Qualifies for state DBT subsidy)',
      'B.Tech / Engineering graduate qualifies for highest ₹10,000/month DBT bracket',
    ],
    lastVerified: '2026-09-20',
  },
  {
    id: 'scheme_naps',
    name: 'National Apprenticeship Promotion Scheme (NAPS)',
    category: 'Central Government Scheme',
    ministryOrDept: 'Ministry of Skill Development and Entrepreneurship (MSDE)',
    portalName: 'Apprenticeship India Portal',
    portalUrl: 'https://www.apprenticeshipindia.gov.in/',
    monthlyStipendInr: '₹9,000 - ₹15,000 / month',
    targetAudience: 'Engineers, Diploma holders, and Vocational graduates across India',
    description: 'National program reimbursing 25% of prescribed stipend directly to candidates engaged in designated tech & engineering apprenticeship trades with public & private enterprises.',
    benefits: [
      'Statutory apprenticeship certificate from Government of India',
      'Industrial exposure in leading public & private tech corporations',
      'Direct stipend co-funding by MSDE',
    ],
    eligible: true,
    reasons: [
      'Age >= 18 meets National Apprenticeship Act eligibility',
      'Eligible for Government of India co-funded 25% stipend subsidy',
    ],
    lastVerified: '2026-09-22',
  },
  {
    id: 'scheme_pmkvy',
    name: 'Pradhan Mantri Kaushal Vikas Yojana 4.0 (PMKVY)',
    category: 'Skill India Mission',
    ministryOrDept: 'National Skill Development Corporation (NSDC)',
    portalName: 'Skill India Digital Hub',
    portalUrl: 'https://www.skillindiadigital.gov.in/',
    monthlyStipendInr: 'Free Training + Assessment & Conveyance Allowance',
    targetAudience: 'Indian youth seeking industry 4.0 technical skills (AI, Cloud, IoT, Robotics)',
    description: 'Covers Industry 4.0 on-demand training tracks in emerging technologies with zero tuition fee and government assessment certification.',
    benefits: [
      '100% sponsored government credential verified on Skill India Digital',
      'National Skill Qualification Framework (NSQF) level 5-7 alignment',
      'Placement assistance across NSDC partner job fairs (Rozgar Melas)',
    ],
    eligible: true,
    reasons: [
      'Eligible for zero-tuition Industry 4.0 NSQF certification under Skill India Mission',
      'Free assessment and NSDC digital verification pass',
    ],
    lastVerified: '2026-09-18',
  },
  {
    id: 'scheme_meity_intern',
    name: 'Digital India Internship Scheme',
    category: 'Central Govt e-Governance Internship',
    ministryOrDept: 'Ministry of Electronics and Information Technology (MeitY)',
    portalName: 'MeitY Digital India Portal',
    portalUrl: 'https://www.meity.gov.in/schemes',
    monthlyStipendInr: '₹10,000 / month',
    targetAudience: 'B.Tech / M.Tech / MCA students with minimum 60% marks in previous examinations',
    description: 'Two-month summer/winter internship program providing exposure to public digital public infrastructure projects (DigiLocker, UPI, Aadhaar, e-Sign, and Open Government Data).',
    benefits: [
      'Mentorship under senior scientists & e-governance directors at MeitY',
      'Certificate of Internship from Government of India',
      'Valuable credential for campus placements and public policy tech careers',
    ],
    eligible: true,
    reasons: [
      'Enrolled in technical degree (B.Tech / Computer Science)',
      'Academic CGPA satisfies minimum 60% requirement',
    ],
    lastVerified: '2026-09-25',
  },
  {
    id: 'scheme_aicte_virtual',
    name: 'AICTE Free Virtual Internship & NEAT Mission',
    category: 'National Educational Alliance for Technology',
    ministryOrDept: 'All India Council for Technical Education (AICTE)',
    portalName: 'AICTE Internship Portal',
    portalUrl: 'https://internship.aicte-india.org/',
    monthlyStipendInr: 'Performance-based + Free Certification',
    targetAudience: 'All AICTE-affiliated college engineering and technical students',
    description: 'Collaborative programs with Google, AWS, Salesforce, and Cisco providing verified project cohorts directly credited to university academic transcripts under NEP 2020.',
    benefits: [
      'Automatic NEP 2020 credit transfer directly recognized by affiliated universities',
      'Industry certificates verified on digital locker',
      'Access to enterprise developer cloud sandbox credits',
    ],
    eligible: true,
    reasons: [
      'Directly mapped to NEP 2020 internship credits on academic transcript',
      'Access to cloud enterprise sandbox and mentor workshops',
    ],
    lastVerified: '2026-09-15',
  },
];

export const roadmapMilestones: RoadmapMilestone[] = [
  {
    id: 'm_foundation',
    phase: 'Learn',
    title: '01 Foundation: Python + DSA',
    description: 'Master core algorithmic problem solving and database indexing foundations.',
    timeframe: 'Target: 4 weeks',
    status: 'Completed',
    tasks: [
      { id: 't1', text: 'Learn core Python data structures and syntax', completed: true, type: 'course' },
      { id: 't2', text: 'Practice 30 fundamental DSA problems (Arrays, HashMaps, Two Pointers)', completed: true, type: 'assessment' },
      { id: 't3', text: 'Proof: verified solutions logged in repository', completed: true, type: 'project' },
    ],
  },
  {
    id: 'm_build',
    phase: 'Build',
    title: '02 Build: 2 Portfolio Projects',
    description: 'Engineer full-stack backend services with authenticated databases and APIs.',
    timeframe: 'Target: 4 weeks',
    status: 'Current',
    tasks: [
      { id: 't4', text: 'Learn REST API design patterns and FastAPI routing', completed: true, linkTo: '/learning/skill-india-fastapi', type: 'course' },
      { id: 't5', text: 'Practice building database models and CRUD endpoints', completed: true, type: 'course' },
      { id: 't6', text: 'Proof: Student Expense API with GitHub repo and demo', completed: false, linkTo: '/projects/student-expense-api', type: 'project' },
    ],
  },
  {
    id: 'm_prove',
    phase: 'Prove',
    title: '03 Prove: Resume + GitHub Proof',
    description: 'Calibrate your resume with quantified metrics, verify GitHub repos, and pass mock screens.',
    timeframe: 'Target: 4 weeks',
    status: 'Upcoming',
    tasks: [
      { id: 't7', text: 'Learn ATS formatting rules and action verb framing', completed: true, linkTo: '/resume/review', type: 'resume' },
      { id: 't8', text: 'Practice mock interview screen on system design', completed: false, linkTo: '/interview', type: 'assessment' },
      { id: 't9', text: 'Proof: ATS score >= 82 and live GitHub project demos', completed: true, type: 'resume' },
    ],
  },
  {
    id: 'm_apply',
    phase: 'Apply',
    title: '04 Apply: Internships + Applications',
    description: 'Dispatch high-match targeted applications with tailored proof evidence.',
    timeframe: 'Target: 4 weeks',
    status: 'Upcoming',
    tasks: [
      { id: 't10', text: 'Learn pre-flight eligibility check requirements', completed: true, linkTo: '/opportunities' },
      { id: 't11', text: 'Practice tailored outreach to hiring teams', completed: false, linkTo: '/opportunities/tracker' },
      { id: 't12', text: 'Proof: 5+ submitted applications logged in tracker', completed: false, linkTo: '/opportunities/tracker' },
    ],
  },
];

export const mockQuestions: MockInterviewQuestion[] = [
  {
    id: 'q1',
    category: 'System Design',
    role: 'AI Systems Engineer',
    question: 'How would you architect a distributed semantic caching layer for a high-traffic LLM API serving 10,000 queries per second?',
    context: 'Assume identical or semantically similar prompts occur frequently. Latency target is sub-15ms for cache hits, and budget is sensitive to unnecessary token generation.',
    keyPointsToCover: [
      'Embedding generation latency and cosine similarity thresholding (e.g. 0.94)',
      'Storage hierarchy (in-memory Redis / KeyDB vs persistent vector index)',
      'Cache invalidation and TTL policies when underlying knowledge changes',
      'Race conditions, cache stampedes, and lock mechanisms (Mutex / Redis Redlock)',
    ],
    timeLimitSeconds: 180,
  },
  {
    id: 'q2',
    category: 'Coding Architecture',
    role: 'Full-Stack Systems Engineer',
    question: 'Explain how you would handle network partition splits in a 3-node Raft consensus cluster. What happens to clients attempting writes on the partitioned minority?',
    context: 'Node A is disconnected from Node B and Node C. Node A was previously the leader. Node B and C establish a new quorum.',
    keyPointsToCover: [
      'Minority node cannot reach quorum (needs at least 2 of 3 votes)',
      'Uncommitted entries remain staged but never committed',
      'Term increment on reconnection and stepping down to follower state',
      'Reconciliation of log differences using AppendEntries RPC index checks',
    ],
    timeLimitSeconds: 180,
  },
  {
    id: 'q3',
    category: 'Behavioral / Leadership',
    role: 'General Software Engineering',
    question: 'Tell me about a time you identified a critical technical bottleneck or architectural flaw late in a project. How did you diagnose it, communicate the tradeoff, and resolve it?',
    context: 'Focus on engineering ownership, quantifiable metrics, and constructive team communication.',
    keyPointsToCover: [
      'Specific profiling tool or diagnostic methodology used',
      'Data-driven communication of impact rather than emotional reaction',
      'Pragmatic compromise balancing delivery timelines and technical debt',
      'Post-mortem and preventative tests established',
    ],
    timeLimitSeconds: 150,
  },
];

export function courseFor(skillId: string): Course | undefined {
  const item = skillsCatalogue.find((s) => s.id === skillId);
  if (!item || !item.mappedCourseId) return undefined;
  return courses.find((c) => c.id === item.mappedCourseId);
}

export function projectsFor(skillId: string): Project[] {
  const item = skillsCatalogue.find((s) => s.id === skillId);
  if (!item || !item.mappedProjectIds) return [];
  return projects.filter((p) => item.mappedProjectIds?.includes(p.id));
}

export function careerWhy(career: CareerPath) {
  return career.whyMatchRationale;
}
